/**
 * Property-Based Tests for Error Message Terminology
 * 
 * Property 9: Error Message Terminology
 * Validates: Requirements 10.2
 * 
 * For any error or warning message generated by the system, the message text 
 * should use "member" or "follow-up member" terminology (not "volunteer") 
 * when referring to participants with follow-up roles.
 */

import * as fc from 'fast-check';
import { ErrorCode, AppError, logError, logWarning } from '../src/services/error-service';

describe('Property 9: Error Message Terminology', () => {
  /**
   * Arbitraries for generating test data
   */
  const errorCodeArb = fc.constantFrom<ErrorCode>(
    ErrorCode.INVALID_INPUT,
    ErrorCode.MISSING_REQUIRED_FIELD,
    ErrorCode.DUPLICATE_MEMBER,
    ErrorCode.MEMBER_NOT_FOUND,
    ErrorCode.NO_AVAILABLE_FOLLOW_UP_MEMBER,
    ErrorCode.INVALID_STATUS_TRANSITION,
    ErrorCode.RETURNER_NOT_IN_SYSTEM,
    ErrorCode.AIRTABLE_API_ERROR,
    ErrorCode.AIRTABLE_RATE_LIMITED,
    ErrorCode.DYNAMODB_ERROR,
    ErrorCode.COGNITO_ERROR,
    ErrorCode.INTERNAL_ERROR,
    ErrorCode.CONFIGURATION_ERROR,
    ErrorCode.TIMEOUT_ERROR
  );

  const errorMessageArb = fc.oneof(
    fc.constant('Follow-up member not found'),
    fc.constant('No available follow-up member'),
    fc.constant('Member capacity exceeded'),
    fc.constant('Follow-up member at capacity'),
    fc.constant('Cannot assign to follow-up member'),
    fc.constant('Follow-up member is inactive'),
    fc.constant('Member not assigned to follow-up member'),
    fc.constant('Invalid member status'),
    fc.constant('Member record not found')
  );

  /**
   * Property 9.1: Error codes should use "MEMBER" terminology, not "VOLUNTEER"
   * 
   * Validates that error code enum values use correct terminology
   */
  it('should use MEMBER terminology in error codes', () => {
    fc.assert(
      fc.property(errorCodeArb, (errorCode) => {
        const codeString = errorCode.toString();
        
        // Property: Error code should not contain "VOLUNTEER"
        expect(codeString).not.toContain('VOLUNTEER');
        
        // Property: If error code relates to follow-up operations, 
        // it should use "MEMBER" or "FOLLOW_UP_MEMBER"
        if (codeString.includes('AVAILABLE') || codeString.includes('FOUND')) {
          const hasMemberTerminology = 
            codeString.includes('MEMBER') || 
            codeString.includes('FOLLOW_UP_MEMBER');
          expect(hasMemberTerminology).toBe(true);
        }
      }),
      { numRuns: 100 }
    );
  });

  /**
   * Property 9.2: Error messages should use "member" or "follow-up member" terminology
   * 
   * Validates that error message text uses correct terminology
   */
  it('should use member terminology in error messages', () => {
    fc.assert(
      fc.property(
        errorCodeArb,
        errorMessageArb,
        (errorCode, message) => {
          const error = new AppError(errorCode, message);
          
          // Property: Error message should not contain "volunteer" (case-insensitive)
          const messageLower = error.message.toLowerCase();
          expect(messageLower).not.toContain('volunteer');
          
          // Property: If message relates to follow-up operations,
          // it should contain "member" or "follow-up member"
          if (
            messageLower.includes('assign') || 
            messageLower.includes('capacity') ||
            messageLower.includes('available') ||
            messageLower.includes('found')
          ) {
            const hasMemberTerminology = 
              messageLower.includes('member') || 
              messageLower.includes('follow-up member');
            expect(hasMemberTerminology).toBe(true);
          }
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * Property 9.3: AppError instances should not contain "volunteer" in any property
   * 
   * Validates that error objects are free of volunteer terminology
   */
  it('should not contain volunteer terminology in error object properties', () => {
    fc.assert(
      fc.property(
        errorCodeArb,
        errorMessageArb,
        fc.option(fc.record({
          operation: fc.string({ minLength: 5, maxLength: 30 }),
          recordId: fc.stringMatching(/^rec[a-zA-Z0-9]{14}$/),
        }), { nil: undefined }),
        (errorCode, message, details) => {
          const error = new AppError(errorCode, message, {
            details: details || undefined,
          });
          
          // Property: Serialized error should not contain "volunteer"
          const errorJson = JSON.stringify(error.toJSON());
          const errorJsonLower = errorJson.toLowerCase();
          expect(errorJsonLower).not.toContain('volunteer');
          
          // Property: Error code should use correct terminology
          expect(error.code).not.toContain('VOLUNTEER');
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * Property 9.4: Warning messages should use "member" terminology
   * 
   * Validates that warning logs use correct terminology
   */
  it('should use member terminology in warning messages', () => {
    const warningMessageArb = fc.oneof(
      fc.constant('Follow-up member approaching capacity limit'),
      fc.constant('Member assignment may be delayed'),
      fc.constant('Follow-up member has high workload'),
      fc.constant('Consider reassigning to another follow-up member'),
      fc.constant('Member capacity threshold reached')
    );

    fc.assert(
      fc.property(warningMessageArb, (warningMessage) => {
        // Property: Warning message should not contain "volunteer"
        const messageLower = warningMessage.toLowerCase();
        expect(messageLower).not.toContain('volunteer');
        
        // Property: Warning should contain "member" terminology
        expect(messageLower).toContain('member');
      }),
      { numRuns: 50 }
    );
  });

  /**
   * Property 9.5: NO_AVAILABLE_FOLLOW_UP_MEMBER error code should exist
   * 
   * Validates that the new error code is defined and uses correct terminology
   */
  it('should have NO_AVAILABLE_FOLLOW_UP_MEMBER error code', () => {
    // Property: Error code enum should contain NO_AVAILABLE_FOLLOW_UP_MEMBER
    expect(ErrorCode.NO_AVAILABLE_FOLLOW_UP_MEMBER).toBeDefined();
    expect(ErrorCode.NO_AVAILABLE_FOLLOW_UP_MEMBER).toBe('NO_AVAILABLE_FOLLOW_UP_MEMBER');
    
    // Property: Old VOLUNTEER error code should not exist
    const errorCodeValues = Object.values(ErrorCode);
    const hasVolunteerCode = errorCodeValues.some(code => 
      typeof code === 'string' && code.includes('VOLUNTEER')
    );
    expect(hasVolunteerCode).toBe(false);
  });

  /**
   * Property 9.6: Error messages with capacity context should use member terminology
   * 
   * Validates that capacity-related errors use correct terminology
   */
  it('should use member terminology in capacity-related error messages', () => {
    const capacityMessageArb = fc.oneof(
      fc.constant('Follow-up member has reached capacity limit'),
      fc.constant('No follow-up members available with capacity'),
      fc.constant('Member capacity limit exceeded'),
      fc.constant('All follow-up members are at capacity'),
      fc.constant('Cannot assign: follow-up member capacity full')
    );

    fc.assert(
      fc.property(capacityMessageArb, (message) => {
        const error = new AppError(
          ErrorCode.NO_AVAILABLE_FOLLOW_UP_MEMBER,
          message
        );
        
        // Property: Message should not contain "volunteer"
        expect(error.message.toLowerCase()).not.toContain('volunteer');
        
        // Property: Message should contain "member" or "follow-up member"
        const messageLower = error.message.toLowerCase();
        const hasMemberTerminology = 
          messageLower.includes('member') || 
          messageLower.includes('follow-up member');
        expect(hasMemberTerminology).toBe(true);
        
        // Property: Error code should use FOLLOW_UP_MEMBER terminology
        expect(error.code).toBe(ErrorCode.NO_AVAILABLE_FOLLOW_UP_MEMBER);
        expect(error.code).toContain('FOLLOW_UP_MEMBER');
      }),
      { numRuns: 50 }
    );
  });

  /**
   * Property 9.7: Logged errors should not contain volunteer terminology
   * 
   * Validates that error logging uses correct terminology
   */
  it('should not log volunteer terminology in error logs', () => {
    // Mock console.error to capture log output
    const originalConsoleError = console.error;
    let loggedOutput = '';
    console.error = jest.fn((output: string) => {
      loggedOutput = output;
    });

    fc.assert(
      fc.property(
        errorCodeArb,
        errorMessageArb,
        (errorCode, message) => {
          const error = new AppError(errorCode, message);
          
          logError(error, {
            operation: 'test-operation',
            timestamp: new Date().toISOString(),
          });
          
          // Property: Logged output should not contain "volunteer"
          expect(loggedOutput.toLowerCase()).not.toContain('volunteer');
          
          // Reset for next iteration
          loggedOutput = '';
        }
      ),
      { numRuns: 50 }
    );

    // Restore console.error
    console.error = originalConsoleError;
  });

  /**
   * Property 9.8: Warning logs should not contain volunteer terminology
   * 
   * Validates that warning logging uses correct terminology
   */
  it('should not log volunteer terminology in warning logs', () => {
    // Mock console.warn to capture log output
    const originalConsoleWarn = console.warn;
    let loggedOutput = '';
    console.warn = jest.fn((output: string) => {
      loggedOutput = output;
    });

    const warningMessageArb = fc.oneof(
      fc.constant('Follow-up member capacity warning'),
      fc.constant('Member assignment delayed'),
      fc.constant('Follow-up member workload high')
    );

    fc.assert(
      fc.property(warningMessageArb, (message) => {
        logWarning(message, {
          operation: 'capacity-check',
          timestamp: new Date().toISOString(),
        });
        
        // Property: Logged output should not contain "volunteer"
        expect(loggedOutput.toLowerCase()).not.toContain('volunteer');
        
        // Property: Logged output should contain "member"
        expect(loggedOutput.toLowerCase()).toContain('member');
        
        // Reset for next iteration
        loggedOutput = '';
      }),
      { numRuns: 50 }
    );

    // Restore console.warn
    console.warn = originalConsoleWarn;
  });
});
